# Generated by Django 4.2.8 on 2026-05-22 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.FloatField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='PaperModule',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'paper_module',
            },
        ),
        migrations.CreateModel(
            name='PaperQuestions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=64)),
                ('question_id', models.CharField(max_length=64)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('marks', models.FloatField(default=0)),
                ('module', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'paper_questions',
            },
        ),
    ]
