# Generated by Django 4.2.8 on 2026-05-22 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorArchive',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=64)),
                ('collector', models.CharField(max_length=64)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'error_archive',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('topic', models.TextField(max_length=1000)),
                ('options', models.TextField(default='[]')),
                ('answer', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('select', 'Select'), ('judge', 'Judge')], default='select', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
