# Generated by Django 4.2.8 on 2026-05-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(default='subjective', max_length=32),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_client_ts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='score',
            name='last_client_ts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='last_save_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='submit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='submitted_client_ts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='graded_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('exam_result_id', 'question_id'), name='uniq_answer_exam_result_question'),
        ),
        migrations.AddConstraint(
            model_name='scoredetail',
            constraint=models.UniqueConstraint(fields=('exam_result_id', 'question_id'), name='uniq_score_detail_exam_result_question'),
        ),
    ]
